"""Generated human views from canonical run state."""

from __future__ import annotations

from pathlib import Path

from .jsonutil import write_text_atomic
from .state import RunState, RunStateValue, TaskState

_HEADER = "<!-- GENERATED BY ECLIPSE HARNESS — DO NOT EDIT -->\n"


def render_active_plan(state: RunState) -> str:
    lines = [
        _HEADER.rstrip(),
        "",
        "# Active plan",
        "",
        f"Run: `{state.run_id}`  ",
        f"Plan revision: `{state.plan_revision}`  ",
        f"Base revision: `{state.base_revision}`  ",
        f"Status: `{state.status.value}`",
        "",
        "## Objective",
        "",
        state.objective,
        "",
        "## Tasks",
        "",
        "| Task | State | Attempts | Reviews | Dependencies |",
        "|---|---|---:|---:|---|",
    ]
    for task_id, task in sorted(state.tasks.items()):
        dependencies = ", ".join(f"`{item}`" for item in task.dependencies) or "—"
        lines.append(
            f"| `{task_id}` | `{task.state.value}` | {task.attempt} | "
            f"{task.review_rounds} | {dependencies} |"
        )
    if not state.tasks:
        lines.append("| — | `planned` | 0 | 0 | — |")
    return "\n".join(lines) + "\n"


def render_handoff(state: RunState) -> str:
    by_state = {
        status: [task_id for task_id, task in sorted(state.tasks.items()) if task.state is status]
        for status in TaskState
    }
    completed = by_state[TaskState.ACCEPTED]
    blocked = by_state[TaskState.BLOCKED] + by_state[TaskState.ESCALATED]
    active_states = {
        TaskState.READY,
        TaskState.RUNNING,
        TaskState.EVIDENCE_PENDING,
        TaskState.REVIEW_PENDING,
        TaskState.READY_FOR_CORRECTION,
    }
    active = [
        task_id for task_id, task in sorted(state.tasks.items()) if task.state in active_states
    ]
    next_action = _next_action(state)
    lines = [
        _HEADER.rstrip(),
        "",
        "# Active handoff",
        "",
        f"Generated from `.eclipse/runs/{state.run_id}/run.json`.",
        "",
        "## Objective",
        "",
        state.objective,
        "",
        "## Current execution",
        "",
        f"- Run: `{state.run_id}`",
        f"- Plan revision: `{state.plan_revision}`",
        f"- Completed tasks: {_ids(completed)}",
        f"- Active tasks: {_ids(active)}",
        f"- Blocked or escalated tasks: {_ids(blocked)}",
        "",
        "## Next action",
        "",
        next_action,
    ]
    return "\n".join(lines) + "\n"


def write_views(state: RunState, output_dir: Path) -> tuple[Path, Path]:
    output_dir.mkdir(parents=True, exist_ok=True)
    active_plan = output_dir / "ACTIVE_PLAN.md"
    handoff = output_dir / "HANDOFF.md"
    write_text_atomic(active_plan, render_active_plan(state))
    write_text_atomic(handoff, render_handoff(state))
    return active_plan, handoff


def _ids(values: list[str]) -> str:
    return ", ".join(f"`{value}`" for value in values) or "—"


def _next_action(state: RunState) -> str:
    priority = (
        (TaskState.ESCALATED, "Resolve escalation for"),
        (TaskState.BLOCKED, "Resolve blocker for"),
        (TaskState.REVIEW_PENDING, "Review"),
        (TaskState.READY_FOR_CORRECTION, "Correct"),
        (TaskState.READY, "Execute"),
        (TaskState.RUNNING, "Resume"),
    )
    for status, verb in priority:
        for task_id, task in sorted(state.tasks.items()):
            if task.state is status:
                return f"{verb} task `{task_id}`."
    if state.status is RunStateValue.ACCEPTED:
        return "All tasks are accepted; prepare final human completion."
    return "Create or revise task contracts."
