"""Adapter rendering and non-destructive installation."""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Iterable

from ..authorization import ensure_repository_bounded, normalize_repo_path
from ..errors import AdapterError
from ..jsonutil import read_text_bounded, write_text_atomic

GENERATED_MARKER = "GENERATED BY ECLIPSE HARNESS — DO NOT EDIT"


@dataclass(frozen=True)
class AdapterArtifact:
    relative_path: str
    content: str


@dataclass(frozen=True)
class InstallAction:
    relative_path: str
    action: str


def install_artifacts(
    root: Path,
    artifacts: Iterable[AdapterArtifact],
    *,
    dry_run: bool = False,
) -> tuple[InstallAction, ...]:
    actions: list[InstallAction] = []
    for artifact in artifacts:
        relative_path = normalize_repo_path(artifact.relative_path)
        _reject_symlink_components(root, relative_path)
        target = ensure_repository_bounded(root, relative_path)
        action = "create"
        if target.exists():
            existing = read_text_bounded(target)
            if existing == artifact.content:
                actions.append(InstallAction(relative_path, "unchanged"))
                continue
            if GENERATED_MARKER not in existing:
                raise AdapterError(
                    f"refusing to overwrite user-owned file {relative_path}; "
                    "generate into another root or merge manually"
                )
            action = "update-generated"
        actions.append(InstallAction(relative_path, action))
        if not dry_run:
            write_text_atomic(target, artifact.content)
    return tuple(actions)


def _reject_symlink_components(root: Path, relative_path: str) -> None:
    current = root.resolve()
    for part in Path(relative_path).parts:
        current = current / part
        if current.is_symlink():
            raise AdapterError(f"refusing generated-file write through symlink: {relative_path}")
